In [4]:
# First of all import tensorflow (always)
import tensorflow as tf

In [19]:
# Let's make some constants! This is the most basic operation. 
# The creation of constant itself is the most basic operation!

# Make a constant that contains 3 and make a constant that contains 3.0 and the type of it is float32.
x = tf.constant(3)
y = tf.constant(3.0, dtype=tf.float32)

# Make a constant list and matrix.
# Give a new shape to them.
const_list = tf.constant([1, 2, 3, 4, 5, 6], dtype=tf.float32, shape=(2, 3))

# If we want to print out the constants then we will get the tensors 
# but we can't see values because we just built the computional graph.
# We defined the operations but we did not run them. These objects
# just represent the results of the operations that will be run.
# Try to print it and check the magic!
print(x)
print(y)
print(const_list)

# So run them! (Just run away from this....)
session = tf.Session()
print(session.run(x))
print(session.run(y))
print(session.run(const_list))

Tensor("Const_25:0", shape=(), dtype=int32)
Tensor("Const_26:0", shape=(), dtype=float32)
Tensor("Const_27:0", shape=(2, 3), dtype=float32)
3
3.0
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:


# We can use other kind of operations like:
#
#
# *   tf.add
# *   tf.multiply
# *   tf.divide
# *   etc
#
# Let's see how the computional graphs are changing in the background. Try it!

z = tf.add(y,tf.divide(y,0.2))
print(session.run(z))
z = tf.multiply(const_list,z)
print(session.run(z))


In [ ]:
# Now we have 3 node in the:[computional graph] and the result will be in c
# (https://drive.google.com/open?id=19P22lK_eiXlHM20yy3RraoQto3IVMxcS)
# Write few line of code what can represent this figure (link above).
# Feel free to choose the value of the constants.
a = tf.constant(3.0)
b = tf.constant(3.0)
c = tf.add(a,b)

# Run the session to calculate the result of computional graph:
print(session.run(c))

# Build a more complex graph: make 4 constant and define the operations between them
aa = tf.constant(2.0)
bb = tf.constant(1.0)
cc = tf.constant(3.0)
dd = tf.constant(4.0)
xx = tf.subtract(dd, bb)
yy = tf.multiply(aa,cc)
result = tf.add(xx,yy)
# Run it as a session: show me how would you do it with the 'with' keyword
with tf.Session() as ss:
    print(ss.run(result))

6.0
3.0
6.0
9.0


In [2]:
# Placeholders: These are like parameters in the computional graph. 
# A placeholder is a promise to provide a value later, like a 
# function argument.
import tensorflow as tf

# Declaration of placeholders:declare two placeholder with the ordinary type
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)

# Define a computional graph: What does it mean? 
# You should define the operation between the created placeholders
z = tf.add(x, y)

# Define the values of placeholders in a dictionary: 
# In this case you give values to your tensors. Just do it!
feed_dict = {x: 8.0, y: 2.0}

# Run it as a session and give in the feed_dictionary in order to load 
# placeholders
with tf.Session() as ss:
    print(ss.run(z,feed_dict))





10.0


In [6]:
# Solving equation with tensorflow:

# Prdefined inputs for the exercise
x = tf.constant([[5., 6.]])
y = tf.Variable(tf.zeros([1, 2])) # Initialize it with zero vector
z = tf.constant([[2.]])
f = tf.constant([[24., 28.]])

# Define the equation : (x+y)*z = q
q = tf.multiply(z,tf.add(x,y))

# Define the squared deviation
sdev = tf.square(f-q)

# Define the training step: 
# use an optimezer and a the minimize function for it 
# The optimizer needs a learning rate
# The minimizer needs the deviation as a parameter too.
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(sdev)

# Define the Op that initializes global variables in the graph
init = tf.global_variables_initializer()

# Run it! Here as usual you have to use the Session with a for-loop for it.
# First of all, determine an iteration number

iter = 5000
with tf.Session() as ss:
    ss.run(init)
    for e in range(iter):
        ss.run(train_step)
    print(ss.run(y))

[[6.999997 7.999997]]


In [11]:
# Let's make a method that will be able to execute linear regression:
# Import that library what need for the plotting first!
import matplotlib.pyplot as plt
import tensorflow as tf

tf.reset_default_graph()
# Write a function with the following paramters:
# function name = simple_linear_regression
def simple_linear_regression():

    # Definition of training data:
    train_x = [3.3, 4.4, 5.5, 6.71, 6.93, 4.168, 9.779, 6.182, 7.59, 2.167,
            7.042, 10.791, 5.313, 7.997, 5.654, 9.27,3.1, 2.0, 2.45, 5.0]
    train_y = [1.7, 2.76, 2.09, 3.19, 1.694, 1.573, 3.366, 2.596, 2.53,
          1.221,2.827, 3.465, 1.65, 2.904, 2.42, 2.94, 1.3, 3.0, 4.2, 4.8]
    
    # Declaration of placeholders for the training datas
    x = tf.placeholder(tf.float32)
    y = tf.placeholder(tf.float32)
    
    # Definition of variables that will contain the weight vector and
    # bias vector that are related to the given linear regression problem
    w = tf.Variable([1.0], name="weight")
    b = tf.Variable([1.0], name="bias")
    
    # build the comp graph: so define the operations between the variables
    pred = tf.multiply(w,x)
    pred = tf.add(w,b)
    
    # define the loss function like: square, subtract
    loss = tf.square(tf.subtract(y,pred))
    
    # define the training step like previously: optimizer, minimizer
    opt = tf.train.AdamOptimizer(0.01).minimize(loss)
    
    #Write the global variables' initializer and the session
    init = tf.global_variables_initializer()
    
    # Let's traint it! Use epochs with a range and after that
    # Execute a training per each point of the training set:
    # So run the session with the optimizer and the training datas in a dict
    # After that calculate the w_opt and the b_opt
    # After that show me the what did you get after the for-loop (print)
    # Create a plot with a figure and its axises
    with tf.Session() as ss:
        ss.run(init)
        for epoch in range(1000):
            for i in range(len(train_x)):
                _ = ss.run(loss, feed_dict={x: train_x[i], y: train_y[i]})
        fig, ax = plt.subplots()
        w_opt = ss.run(w)
        b_opt = ss.run(b)
    # let's calculate our predictions: make a list for prediction results
    # Write a for-loop for it with your input data's length,
    # where you will insert your results into your prediction list
    prediction = []
    for i in range(len(train_x)):
        prediction.append(train_x * w_opt + b_opt)
    
    # Disply the result with the ploting's function
    ax.plot(train_x, train_y, 'ro')
    ax.plot(train_x, prediction, 'bo')
    plt.show()
    
simple_linear_regression() 